name: CI

on: [push, pull_request]

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --registry https://registry.npmjs.org
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
